### PR TITLE
course support for images

### PR DESCRIPTION
**Pull request by smilesthesad**
## Implementation Description
You can now add images to courses themselves, and they are the default images for the course modules if there are no course module images set

## Screenshots
Visual depiction of PR

https://user-images.githubusercontent.com/36215359/194804032-8b787456-3df0-4341-aed3-2c40d1dc7ade.mov

## What should reviewers focus on?
- you can edit/create a course, and upload an image by clicking save in the edit modal 
- The image should persist

## Testing Procedure
- Create a new course, create some modules in that course
- Upload an image
- Ensure you can see that image in the course preview 
- Ensure that you can see that image when you submit the course image, and that refreshing still contains it

## Checklist
- [X] Ensure code follows style guide by running the linters
- [X] I have updated the documentation or deemed it unnecessary
- [X] I have linked the relevant issue in this PR
- [X] I have requested a review from the PL, as well as other dev(s) (and designers if necessary)

### CODE REVIEW

**Review by draymond63 — CHANGES_REQUESTED** [review]
Everything you've done looks great! The only thing I'd do now is go through the learner pages and make it so the course images show up there.

1. Course browsing page (on the tiles)
2. Course overview page (in the floating card)
3. Lesson viewer page (as a backup for the module image, same as what you did for the module preview here)
4. Module completion page (as a backup, ...)

**Review by jfdoming — COMMENTED** [review]
Looks fine, but if we're combining the module/course image upload endpoints, we should probably change the path used from "moduleImages" to something else.

**Review by draymond63 — APPROVED** [review]
Everything looks good, although I get `no such file or directory` errors on upload when I run it locally. If it works for you though, I'm happy!

**Comment by smilesthesad** [comment]
> Everything looks good, although I get `no such file or directory` errors on upload when I run it locally. If it works for you though, I'm happy!

thats weird. @jfdoming are you able to get it working locally? it works fine on my end and the images stay available as well

**Review by jfdoming — APPROVED** [review]

**Pull request merged**
