### PR TITLE
[RHS-158]: Add linter pre-commit hooks

### PR DESCRIPTION
**Pull request by jfdoming**
## Implementation Description
- Hint at devs to install pre-commit on docker startup
- Lint on pre-commit
- Use linter cache to speed up pre-commit hooks

## Screenshots
image

## What should reviewers focus on?
- Can you think of cleaner/faster ways to implement this?

## Testing Procedure
- Is it secure? Could nefarious users access/break it?
A: Not designed to be secure, only hint to install pre-commit hooks for users.

## Checklist
- [x] Ensure code follows style guide by running the linters (:D)
- [x] I have updated the documentation or deemed it unnecessary
- [x] I have linked the relevant issue in this PR
- [x] I have requested a review from the PL, as well as other dev(s) (and designers if necessary)

### CODE REVIEW

**Comment by mslwang** [comment]
Would it be possible to try to use [husky](https://www.npmjs.com/package/husky) for pre-commits? It integrates naturally into a js/ts project, so we might be able to include it as part of installs somewhere.

I've been using a vscode extension for watching files, but I like the idea of using pre-commit hooks since it happens all at once.

**Review by e-wai — COMMENTED** [review]
Says there's a symbolic link at `utils.sh` now, what does that do for us?

**Comment by jfdoming** [comment]
> Says there's a symbolic link at `utils.sh` now, what does that do for us?

In theory it's not necessary, but I didn't want to break people's local setups in case they were using `utils.sh` in their own environment configuration.

**Comment by mslwang** [comment]
Would it be possible to get instructions on how to set this up? I think it'd be great to get this pushed out ASAP so we can start linting better sooner! We can definitely consider husky later.

**Review by mslwang — APPROVED** [review]

**Pull request merged**
