### PR TITLE
[RHS-173]: Enable debugging

### PR DESCRIPTION
**Pull request by jfdoming**
## Implementation Description
A feature for the development environment requested by devs was to be able to connect to the frontend/backend via a debugger. This PR adds some configuration to the repository to support this.
- [RHS-173]: Enable debug mode for node while developing
- [RHS-173]: Add launch configurations for devs using VS Code

## Screenshots
N/A

## What should reviewers focus on?
- How do you feel about permanently running in `--inspect` mode for all local development? Is it worth it in order to prevent having to commit a `settings.json` with extra command configuration?

## Testing Procedure
Feel free to check this out locally and try it yourself. The normal development flow is unchanged (run `docker-compose up --build`), but you should be able to run additional debug configurations from the tab on the left-hand side of VS Code.

## Things to Note
N/A

## Checklist
- [x] Ensure code follows style guide by running the linters
- [x] I have updated the documentation or deemed it unnecessary
- [x] I have linked the relevant issue in this PR
- [x] I have requested a review from the PL, as well as other dev(s) (and designers if necessary)

### CODE REVIEW

**Review by mslwang — APPROVED** [review]
lgtm

**Comment by mslwang** [comment]
Could be good to add some instructions to the README just in case someone hasn't used a vscode debugger before, but it's pretty straightforward overall, so we could at least state its existence in the README.

**Comment by jfdoming** [comment]
> Could be good to add some instructions to the README just in case someone hasn't used a vscode debugger before, but it's pretty straightforward overall, so we could at least state its existence in the README.

Yep, I updated the Notion workspace documentation in the Onboarding section with this information, since it didn't seem to fit in the README based on the current content. I think it would be better to direct people to the Notion workspace if possible, because that way we can keep all our docs in one place.

**Comment by mslwang** [comment]
> > Could be good to add some instructions to the README just in case someone hasn't used a vscode debugger before, but it's pretty straightforward overall, so we could at least state its existence in the README.
> 
> Yep, I updated the Notion workspace documentation in the Onboarding section with this information, since it didn't seem to fit in the README based on the current content. I think it would be better to direct people to the Notion workspace if possible, because that way we can keep all our docs in one place.

Nice, just checked the notion, looks good!

**Pull request merged**
