### PR TITLE
Use Vault for our team secrets

### PR DESCRIPTION
**Pull request by jfdoming**
## Implementation Description
We now have a Vault KV-store set up for our team! This PR updates the dev environment to fetch secrets from our Vault, so that we don't have to put secrets on our public Notion.

- Update post-merge hook to be RHS-specific
- Update setup script name to be more clear
- Add local environment file so people can use their own MongoDB

## Screenshots
N/A

## What should reviewers focus on?
- 

## Testing Procedure
- What test(s) should we run to make sure your code works?
   - What ways could the input be wrong?
   - Is it secure? Could nefarious users access/break it?

## Things to Note
- Additional dependencies/libraries you've added?
- Things you'd want to know when coming back to the code after a few months

## Checklist
- [ ] Ensure code follows style guide by running the linters
- [x] I have updated the documentation or deemed it unnecessary
- [ ] I have linked the relevant issue in this PR
- [ ] I have requested a review from the PL, as well as other dev(s) (and designers if necessary)

### CODE REVIEW

**Comment by e-wai** [comment]
Could you add a quick "how-to" note for setting up the repo? (The README is not super helpful about this part)

**Comment by jfdoming** [comment]
> Could you add a quick "how-to" note for setting up the repo? (The README is not super helpful about this part)

Updated, thanks for pointing this out! I had updated the Notion docs but it completely slipped my mind that the README was also a source of documentation. 🤦‍♂️

**Comment by mslwang** [comment]
I don't have the full context, by why was the setup file replaced? It seems like it's still the same in starter code.

**Comment by jfdoming** [comment]
> I don't have the full context, by why was the setup file replaced? It seems like it's still the same in starter code.

It should be a rename, not a replacement, but the main change is that we no longer need to update the hook on every run, and the script will actually execute the hook now.

**Comment by mslwang** [comment]
> > I don't have the full context, by why was the setup file replaced? It seems like it's still the same in starter code.
> 
> It should be a rename, not a replacement, but the main change is that we no longer need to update the hook on every run, and the script will actually execute the hook now.

Is that reflected in the general documentation with that in mind? Or is this specific to our project?

**Comment by jfdoming** [comment]
> > > I don't have the full context, by why was the setup file replaced? It seems like it's still the same in starter code.
> > 
> > 
> > It should be a rename, not a replacement, but the main change is that we no longer need to update the hook on every run, and the script will actually execute the hook now.
> 
> Is that reflected in the general documentation with that in mind? Or is this specific to our project?

The general documentation doesn't mention the details of this setup script. It's present but not documented in the starter code repository. This change is specific to our project but I might try to upstream these changes if people like it.

**Comment by jfdoming** [comment]
Closing as not necessary.

**Pull request closed without merging**
