### PR TITLE
Module viewer mobile support

### PR DESCRIPTION
**Pull request by jfdoming**
## Implementation Description
- Make sidebar fill screen on smaller devices
- Adjust course padding depending on screen size
- Adjust size of videos to always fit on screen
- [unrelated bug]: Text blocks should not be editable
- Make module completion page responsive

## What should reviewers focus on?
- 

## Testing Procedure
Manual testing on smaller screen sizes (can use devtools to easily try many sizes).

## Things to Note
- Additional dependencies/libraries you've added?
- Things you'd want to know when coming back to the code after a few months

## Checklist
- [x] Ensure code follows style guide by running the linters
- [x] I have updated the documentation or deemed it unnecessary
- [x] I have linked the relevant issue in this PR
- [x] I have requested a review from the PL, as well as other dev(s) (and designers if necessary)

### CODE REVIEW

**Review by draymond63 — CHANGES_REQUESTED** [review]
I think the remain issues are:
1. Column component really squishes both things inside it. Maybe we should display its children sequentially on mobile?
2. Quiz & Matching component should reduce their padding on mobile.
3. How can you hide the sidebar without clicking on a lesson? If you are on the module completion page there doesn't seem to be a way to hide it without going back to a lesson. There should be some close button or something.

**Comment by jfdoming** [comment]
> I think the remain issues are:
> 
> 1. Column component really squishes both things inside it. Maybe we should display its children sequentially on mobile?
> 2. Quiz & Matching component should reduce their padding on mobile.
> 3. How can you hide the sidebar without clicking on a lesson? If you are on the module completion page there doesn't seem to be a way to hide it without going back to a lesson. There should be some close button or something.

1. Will look into it.
2. 👍 
3. Is this a necessary feature? IMO having this sort of chevron icon in full-screen mode looks kinda weird. People can just click on the lesson they're currently in if they want to close the menu. I can add it back if you think it's necessary though.

**Comment by draymond63** [comment]
3. I'd definitely prefer to have the ability, but it isn't essential. Whatever you think is best

**Comment by jfdoming** [comment]
> 3. I'd definitely prefer to have the ability, but it isn't essential. Whatever you think is best

I'll spend a little time looking into whether there's a solution with a better UX

**Review by draymond63 — APPROVED** [review]
Looks good!

**Pull request merged**
